### ISSUE TITLE
Validación de las vistas

### ISSUE THREAD

**Issue by Rankoo** [1andrey3/ACS#9]
implementar una validación en el cual el usuario solo pueda acceder a vistas relacionadas a su cargo

**Comment by Rankoo** [comment]
issue terminado con éxito, en el issue se pudo detectar fallos con respecto al uso de las variables de sesión, fallos arreglados, sin embargo recomendaría que le echaran un ojo a la configuración de las cookies

**Comment by leoneloliveros** [comment]
#3
